/**
 * words.conjugations (migrations/016_add_words_conjugations.sql), as
 * generated by supabase/functions/_shared/conjugationCore.ts -- this mirrors
 * that file's StoredConjugations, which the app can't import directly (it
 * lives in the Deno tree). Keep the two in sync; `version` exists so a
 * future shape change can be told apart from this one.
 */

/**
 * A person key: 'je' ... 'elles' for French. Deliberately a plain string --
 * which persons exist is per-language data (src/constants/conjugation.ts),
 * so German's ich/du/... plug in without touching this type.
 */
export type Person = string;

/** One accepted form, or several accepted variants -- the first is canonical. */
export type PersonForms = string | string[];

export interface Conjugations {
  version: number;
  source: 'lefff' | 'llm';
  /** Without any reflexive pronoun: "lever" for "se lever". */
  infinitive: string;
  pronominal: boolean;
  /** Aspirated h (haïr): blocks "je" -> "j'" before an h. */
  hAspire: boolean;
  auxiliary: 'etre' | 'avoir';
  /** Tense key (e.g. 'present', 'passe_compose') -> person -> forms. A person the verb lacks is absent. */
  tenses: Partial<Record<string, Partial<Record<Person, PersonForms>>>>;
}
